/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SaGarDetTillRouteImport } from './routes/sa-gar-det-till'
import { Route as OmRouteImport } from './routes/om'
import { Route as CaseRouteImport } from './routes/case'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TjansterOptimeradeKampanjerRouteImport } from './routes/tjanster.optimerade-kampanjer'
import { Route as TjansterDigitalaSystemAiRouteImport } from './routes/tjanster.digitala-system-ai'
import { Route as TjansterAffarsutvecklingRouteImport } from './routes/tjanster.affarsutveckling'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SaGarDetTillRoute = SaGarDetTillRouteImport.update({
  id: '/sa-gar-det-till',
  path: '/sa-gar-det-till',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseRoute = CaseRouteImport.update({
  id: '/case',
  path: '/case',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TjansterOptimeradeKampanjerRoute =
  TjansterOptimeradeKampanjerRouteImport.update({
    id: '/tjanster/optimerade-kampanjer',
    path: '/tjanster/optimerade-kampanjer',
    getParentRoute: () => rootRouteImport,
  } as any)
const TjansterDigitalaSystemAiRoute =
  TjansterDigitalaSystemAiRouteImport.update({
    id: '/tjanster/digitala-system-ai',
    path: '/tjanster/digitala-system-ai',
    getParentRoute: () => rootRouteImport,
  } as any)
const TjansterAffarsutvecklingRoute =
  TjansterAffarsutvecklingRouteImport.update({
    id: '/tjanster/affarsutveckling',
    path: '/tjanster/affarsutveckling',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case': typeof CaseRoute
  '/om': typeof OmRoute
  '/sa-gar-det-till': typeof SaGarDetTillRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tjanster/affarsutveckling': typeof TjansterAffarsutvecklingRoute
  '/tjanster/digitala-system-ai': typeof TjansterDigitalaSystemAiRoute
  '/tjanster/optimerade-kampanjer': typeof TjansterOptimeradeKampanjerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case': typeof CaseRoute
  '/om': typeof OmRoute
  '/sa-gar-det-till': typeof SaGarDetTillRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tjanster/affarsutveckling': typeof TjansterAffarsutvecklingRoute
  '/tjanster/digitala-system-ai': typeof TjansterDigitalaSystemAiRoute
  '/tjanster/optimerade-kampanjer': typeof TjansterOptimeradeKampanjerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case': typeof CaseRoute
  '/om': typeof OmRoute
  '/sa-gar-det-till': typeof SaGarDetTillRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tjanster/affarsutveckling': typeof TjansterAffarsutvecklingRoute
  '/tjanster/digitala-system-ai': typeof TjansterDigitalaSystemAiRoute
  '/tjanster/optimerade-kampanjer': typeof TjansterOptimeradeKampanjerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case'
    | '/om'
    | '/sa-gar-det-till'
    | '/sitemap.xml'
    | '/tjanster/affarsutveckling'
    | '/tjanster/digitala-system-ai'
    | '/tjanster/optimerade-kampanjer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case'
    | '/om'
    | '/sa-gar-det-till'
    | '/sitemap.xml'
    | '/tjanster/affarsutveckling'
    | '/tjanster/digitala-system-ai'
    | '/tjanster/optimerade-kampanjer'
  id:
    | '__root__'
    | '/'
    | '/case'
    | '/om'
    | '/sa-gar-det-till'
    | '/sitemap.xml'
    | '/tjanster/affarsutveckling'
    | '/tjanster/digitala-system-ai'
    | '/tjanster/optimerade-kampanjer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseRoute: typeof CaseRoute
  OmRoute: typeof OmRoute
  SaGarDetTillRoute: typeof SaGarDetTillRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TjansterAffarsutvecklingRoute: typeof TjansterAffarsutvecklingRoute
  TjansterDigitalaSystemAiRoute: typeof TjansterDigitalaSystemAiRoute
  TjansterOptimeradeKampanjerRoute: typeof TjansterOptimeradeKampanjerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sa-gar-det-till': {
      id: '/sa-gar-det-till'
      path: '/sa-gar-det-till'
      fullPath: '/sa-gar-det-till'
      preLoaderRoute: typeof SaGarDetTillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case': {
      id: '/case'
      path: '/case'
      fullPath: '/case'
      preLoaderRoute: typeof CaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjanster/optimerade-kampanjer': {
      id: '/tjanster/optimerade-kampanjer'
      path: '/tjanster/optimerade-kampanjer'
      fullPath: '/tjanster/optimerade-kampanjer'
      preLoaderRoute: typeof TjansterOptimeradeKampanjerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjanster/digitala-system-ai': {
      id: '/tjanster/digitala-system-ai'
      path: '/tjanster/digitala-system-ai'
      fullPath: '/tjanster/digitala-system-ai'
      preLoaderRoute: typeof TjansterDigitalaSystemAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjanster/affarsutveckling': {
      id: '/tjanster/affarsutveckling'
      path: '/tjanster/affarsutveckling'
      fullPath: '/tjanster/affarsutveckling'
      preLoaderRoute: typeof TjansterAffarsutvecklingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseRoute: CaseRoute,
  OmRoute: OmRoute,
  SaGarDetTillRoute: SaGarDetTillRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TjansterAffarsutvecklingRoute: TjansterAffarsutvecklingRoute,
  TjansterDigitalaSystemAiRoute: TjansterDigitalaSystemAiRoute,
  TjansterOptimeradeKampanjerRoute: TjansterOptimeradeKampanjerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
